### ISSUE TITLE
[Improvement] README text shown on notes of the workflow step

### ISSUE THREAD

**Issue by Acidham** [BenjaminOddou/alfred-folderify#2]
The First workflow step shows README text. I am not certain how the text went into those boxes
<img width="272" alt="Screenshot 2023-03-22 at 07 26 08" src="https://user-images.githubusercontent.com/17712121/226819872-62a038d2-7496-47b6-a6d5-74b77dfc66ea.png">

The boxes are mainly here to explain what the step is doing, rather than writing where to file issues.

**Comment by BenjaminOddou** [comment]
@Acidham, these texts aren't really necessary indeed. I'll remove that in the next release. If you right click on the box you have the option `edit notes` (where the text is located).

**Comment by Acidham** [comment]
I am aware of how to change it, but I thought as an improvement for other users.

Another improvement: I am seeing you addicted to emoji icons ;) but less would be more ;)
